[package]
name = "crossed_wires"
version = "0.1.0"
authors = ["Dimension4 <Dimension4@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.22.0"